services:
  book:
    container_name: book-service
    build:
      context: .
    env_file:
      - ./env_files/.env
    ports:
      - 8100:8100
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: db
    restart: always
    env_file:
      - ./env_files/.env
    ports:
      - '3310:3306'
    volumes:
      - mysql-volume:/var/lib/mysql

volumes:
  mysql-volume:
    driver: local
