spring:
  application:
    name: book-service
#  config:
#    import: optional:configserver:http://localhost:8888/
#  cloud:
#    config:
#      profile: dev
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  management:
    tracing:
      sampling:
        probability: 1.0

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    readinessState:
      enabled: true
    livenessState:
      enabled: true

resilience4j:
    retry:
      instances:
        foo-bar:
          maxAttempts: 4
          waitDuration: 5s
    ratelimiter:
      instances:
        foot-rate:
          limitForPeriod: 5
          limitRefreshPeriod: 10s
          timeoutDuration: 7s

springdoc:
  api-docs:
    path: /book-service/v3/api-docs
  swagger-ui:
    url: /book-service/v3/api-docs

logging:
  level:
    root: INFO

server:
  port: 8100