apiVersion: v1
kind: Service
metadata:
  labels:
    app: book-service
  name: book-service
  namespace: default
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - nodePort: 32330
      port: 8100
      protocol: TCP
      targetPort: 8100
  selector:
    app: book-service
  sessionAffinity: None
  type: LoadBalancer