CREATE TABLE book (
    id BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    author VARCHAR(255) NOT NULL,
    launch_date DATETIME NOT NULL,
    price DECIMAL(65, 2) NOT NULL,
    title VARCHAR(255) NOT NULL
);